### ISSUE TITLE
桌搭投票系统

### ISSUE THREAD

**Issue by LazuliKao** [nbtca/Roadmap#19]
桌搭：内网上传到NAS里面
投票：暂定腾讯问卷
- 不需要登录等步骤，一人一票
![Image](https://github.com/user-attachments/assets/9b912c46-103d-4330-873b-ba1c8ad8f25f)

**Comment by gentlelyyli** [comment]
准备拍点照片实践一下

**Comment by gentlelyyli** [comment]
协会内部拍了一些照片，尝试过一下流程

**Comment by LazuliKao** [comment]
https://wj.qq.com/s2/16813256/f184/
